[package]
name = "loadingbar"
version = "1.0.0"
edition = "2021"
description = "A simple loading bar for the terminal"
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
